[build-system]
build-backend = ''
requires = []

[project]
name = 'sadsa'
version = '0.1.0'
description = ''
readme = 'README.md'
requires-python = '^3.9'
keywords = []
authors = [{name = 'Sebastian Barrios', email = 'sbarrios93@gmail.com'}]
classifiers = []
dependencies = []
dynamic = []

[tool]
