# Poetry pyproject.toml: https://python-poetry.org/docs/pyproject/
[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry_core>=1.0.0"]

[tool.poetry]
authors = ["self <sbarrios93@gmail.com>"]
description = "Amazon YNAB is a reconciler that scrapes Amazon orders and adds memo info on each corresponding YNAB transaction"
homepage = "https://github.com/sbarrios93/amazon-ynab"
license = "MIT"
name = "amazon-ynab"
readme = "README.md"
repository = "https://github.com/sbarrios93/amazon-ynab"
version = "0.2.0"

# Keywords description https://python-poetry.org/docs/pyproject/#keywords
keywords = [] #! Update me

# Pypi classifiers: https://pypi.org/classifiers/
classifiers = [
    #! Update me
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.scripts]
# Entry points for the package https://python-poetry.org/docs/pyproject/#scripts
"amazon-ynab" = "amazon_ynab.__main__:app"

[tool.poetry.dependencies]
python = "^3.10"

beautifulsoup4 = "^4.11.1"
nltk = "^3.7"
rich = "^12.5.1"
selenium = "^4.1.5"
typer = { extras = ["all"], version = "^0.6.1" }
types-beautifulsoup4 = "^4.11.4"
webdriver-manager = "^3.8.2"
types-requests = "^2.28.8"

[tool.poetry.dev-dependencies]
bandit = "^1.7.4"
black = { version = "^22.3.0", allow-prereleases = true }
coverage = "^6.4.4"
coverage-badge = "^1.1.0"
darglint = "^1.8.1"
isort = { extras = ["colors"], version = "^5.10.1" }
mypy = "^0.971"
mypy-extensions = "0.4.3"
pre-commit = "^2.20.0"
prospector = "^1.7.7"
pydocstyle = "^6.1.1"
pyflakes = "^2.5.0"
pylint = "^2.14.5"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-html = "^3.1.1"
pyupgrade = "^2.37.3"
safety = "^2.1.1"
types-PyYAML = "^6.0.11"
types-selenium = "^3.141.9"
ipykernel = "^6.13.0"

[tool.coverage.run]
source = ["tests"]
